name: Build packages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      SYNCTHING_TAG: v1.29.6
    steps:
    - name: Set Syncthing version from source
      run: echo "SYNCTHING_TAG=$(curl https://api.github.com/repos/syncthing/syncthing/tags -s | jq '.[0].name' -r)" >> $GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create Syncthing build container
      run: make build-syncthing-container

    - name: Create QDK build container
      run: make build-qdk-container

    - name: Create Syncthing QPKG
      run : make out/pkg

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Syncthing-${{ env.SYNCTHING_TAG }}-QPKG-all
        path: out/pkg/
